from django.db import models
import datetime

def current_date():
    return datetime.date.today()

# Create your models here.
class Schedule(models.Model):
    date    = models.DateField(primary_key=True, null=True, blank=False, verbose_name='Date', default=current_date)
    time_1  = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 1')
    time_2  = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 2')
    time_3  = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 3')
    time_4  = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 4')
    time_5  = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 5')
    time_6  = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 6')
    time_7  = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 7')
    time_8  = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 8')
    time_9  = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 9')
    time_10 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 10')
    time_11 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 11')
    time_12 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 12')
    time_13 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 13')
    time_14 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 14')
    time_15 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 15')
    time_16 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 16')
    time_17 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 17')
    time_18 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 18')
    time_19 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 19')
    time_20 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 20')
    time_21 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 21')
    time_22 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 22')
    time_23 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 23')
    time_24 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 24')
    time_25 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 25')
    time_26 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 26')
    time_27 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 27')
    time_28 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 28')
    time_29 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 29')
    time_30 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 30')
    time_31 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 31')
    time_32 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 32')
    time_33 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 33')
    time_34 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 34')
    time_35 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 35')
    time_36 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 36')
    time_37 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 37')
    time_38 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 38')
    time_39 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 39')
    time_40 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 40')
    time_41 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 41')
    time_42 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 42')
    time_43 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 43')
    time_44 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 44')
    time_45 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 45')
    time_46 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 46')
    time_47 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 47')
    time_48 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 48')
    time_49 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 49')
    time_50 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Time 50')

    
