# Generated by Django 2.2.3 on 2019-08-01 21:33

from django.db import migrations, models
import schedule.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('date', models.DateField(default=schedule.models.current_date, primary_key=True, serialize=False, verbose_name='Date')),
                ('time_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 1')),
                ('time_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 2')),
                ('time_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 3')),
                ('time_4', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 4')),
                ('time_5', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 5')),
                ('time_6', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 6')),
                ('time_7', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 7')),
                ('time_8', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 8')),
                ('time_9', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 9')),
                ('time_10', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 10')),
                ('time_11', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 11')),
                ('time_12', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 12')),
                ('time_13', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 13')),
                ('time_14', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 14')),
                ('time_15', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 15')),
                ('time_16', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 16')),
                ('time_17', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 17')),
                ('time_18', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 18')),
                ('time_19', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 19')),
                ('time_20', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 20')),
                ('time_21', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 21')),
                ('time_22', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 22')),
                ('time_23', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 23')),
                ('time_24', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 24')),
                ('time_25', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 25')),
                ('time_26', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 26')),
                ('time_27', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 27')),
                ('time_28', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 28')),
                ('time_29', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 29')),
                ('time_30', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 30')),
                ('time_31', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 31')),
                ('time_32', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 32')),
                ('time_33', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 33')),
                ('time_34', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 34')),
                ('time_35', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 35')),
                ('time_36', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 36')),
                ('time_37', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 37')),
                ('time_38', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 38')),
                ('time_39', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 39')),
                ('time_40', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 40')),
                ('time_41', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 41')),
                ('time_42', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 42')),
                ('time_43', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 43')),
                ('time_44', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 44')),
                ('time_45', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 45')),
                ('time_46', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 46')),
                ('time_47', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 47')),
                ('time_48', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 48')),
                ('time_49', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 49')),
                ('time_50', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time 50')),
            ],
        ),
    ]
