# Generated by Django 2.2.3 on 2019-08-02 00:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Time 0'),
        ),
    ]
