# Generated by Django 2.2.3 on 2019-08-03 01:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20190801_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='slot_1',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 1'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_10',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 10'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_11',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 11'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_12',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 12'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_13',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 13'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_14',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 14'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_15',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 15'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_16',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 16'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_17',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 17'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_18',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 18'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_19',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 19'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_2',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 2'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_20',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 20'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_21',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 21'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_22',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 22'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_23',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 23'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_24',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 24'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_25',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 25'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_26',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 26'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_27',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 27'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_28',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 28'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_29',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 29'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_3',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 3'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_30',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 30'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_31',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 31'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_32',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 32'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_33',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 33'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_34',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 34'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_35',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 35'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_36',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 36'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_37',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 37'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_38',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 38'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_39',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 39'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_4',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 4'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_40',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 40'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_41',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 41'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_42',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 42'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_43',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 43'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_44',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 44'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_45',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 45'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_46',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 46'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_47',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 47'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_48',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 48'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_49',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 49'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_5',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 5'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_50',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 50'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_6',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 6'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_7',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 7'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_8',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 8'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_9',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'modality': '', 'name': '', 'phone': '', 'slot': 'ttt', 'status': ''}, verbose_name='Slot 9'),
        ),
    ]
