# Generated by Django 2.2.3 on 2019-08-03 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20190803_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='slot_49',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='slot_50',
        ),
    ]
